version: '3.4'

services:
  gremlin:
      image: barrman/gremlin-server
      ports:
        - '8182:8182'
  
  graph-notebook:
    image: barrman/graph-notebook:latest
    ports:
      - "8888:8888"
    depends_on:
      - gremlin