version: '3.4'

services:
  gremlin:
      image: tinkerpop/gremlin-server
      ports:
        - '8182:8182'
      volumes:
        - ./gremlin/config:/opt/gremlin-server/conf
        - ./gremlin/scripts:/opt/gremlin-server/scripts
  
  graph-notebook:
    image: barrman/graph-notebook:latest
    ports:
      - "8888:8888"
    depends_on:
      - gremlin