export const LOAD_DIFFS_START = 'LOAD_DIFFS_START';
export const LOAD_DIFFS_COMPLETE = 'LOAD_DIFFS_COMPLETE';
export const SET_HIGHLIGHTED_LINE = 'SET_HIGHLIGHTED_LINE';
export const UNSET_HIGHLIGHTED_LINE = 'UNSET_HIGHLIGHTED_LINE';